### DISCUSSION TITLE
Octopus Energy - Flux Tariffs Work Mode Automation

### DISCUSSION THREAD

**Discussion by StealthChesnut** [nathanmarlor/foxess_modbus#158] [Ideas]
The following HA Automation may be useful for anyone on the same tariff. During the Peak the import and export rates are high, so rather than charge the battery you are better off exporting any surplus.

Hopefully I've remembered everything!
First, read this / watch the youtube video for this article - it goes into how to set up helpers. https://www.speaktothegeek.co.uk/2023/02/off-peak-tariffs-in-home-assistants-energy-dashboard/

You will need to set up 4x Time helpers:
Flux Eco Start
Flux Eco End
Flux Peak Start
Flux Peak End

and 6x Utility Meters:
Electricity Export eco
Electricity Export day
Electricity Export peak
Electricity Import eco
Electricity Import day
Electricity Import peak

Automation - copy and paste this into the new automation in step 3 from the article:
```
alias: "Energy: Octpus Flux Tariffs"
description: ""
trigger:
  - platform: time
    at: input_datetime.flux_eco_start
    variables:
      tariff: eco
      workmode: Self Use
  - platform: time
    at: input_datetime.flux_eco_end
    variables:
      tariff: day
      workmode: Self Use
  - platform: time
    at: input_datetime.flux_peak_start
    variables:
      tariff: peak
      workmode: Feed-in First
  - platform: time
    at: input_datetime.flux_peak_end
    variables:
      tariff: day
      workmode: Self Use
action:
  - service: select.select_option
    target:
      entity_id: select.electricity_import
    data:
      option: "{{ tariff }}"
  - service: select.select_option
    target:
      entity_id: select.electricity_export
    data:
      option: "{{ tariff }}"
  - service: select.select_option
    target:
      entity_id: select.work_mode
    data:
      option: "{{ workmode }}"
mode: single
```
