### DISCUSSION TITLE
Migrating over from StealthChesnut integration (finally) - how to avoid duplicate sensors?

### DISCUSSION THREAD

**Discussion by calum-mcfarlane** [nathanmarlor/foxess_modbus#342] [Support] [answered]
Finally got around to trying to migrate to this integration, following Dave Foster's directions [here](https://github.com/nathanmarlor/foxess_modbus/wiki/Migrating-from-HA-FoxESS-Modbus).

I removed the **modbus: !include custom_components/foxess/modbus485.yaml** line from my configuration.yaml, as well as the other custom template sensors defined there (see Sensors Removed, below). 

I left in the **utility_meter** section, as well as all the **integration** sensors (each included in their own sections)

Once I'd done this I restarted HA, confirmed that the dashboards were all showing "Not available" and then installed foxess_modbus from HACS.

The install went fine, but after restarting I found that I had duplicate sensors all over the show with the dreaded "_2" appended. 

I'd taken a full image back of my HA VM before I started so I've gone back to that for now, but I'm wondering what I did wrong in my process - do I need to delete the old entities somehow before installing the integration from HACS?

**Sensors Removed**
```
- name: "Battery Discharge"
      unique_id: foxess_inv1_battery_discharge
      device_class: "power"
      unit_of_measurement: "kW"
      state: >
          {% if (states('sensor.battery_discharge_power') | float(default=0) ) > 0 %}
          {{ states('sensor.battery_discharge_power') | float(default=0) * 1 }}
          {% else %}
          0 
          {% endif %}
    - name: "Battery Charge"
      unique_id: foxess_inv1_battery_charge
      device_class: "power"
      unit_of_measurement: "kW"
      state: >
          {% if (states('sensor.battery_discharge_power') | float(default=0) ) < 0 %}
          {{ states('sensor.battery_discharge_power') | float(default=0) * -1 }}
          {% else %}
          0 
          {% endif %}

    - name: "Grid Consumption"
      unique_id: foxess_inv1_grid_consumption
      device_class: "power"
      unit_of_measurement: "kW"
      state: >
          {% if (states('sensor.grid_ct') | float(default=0) ) < 0 %}
          {{ states('sensor.grid_ct') | float(default=0) * -1 }}
          {% else %}
          0 
          {% endif %}
    - name: "PV Power Now"
      unique_id: foxess_inv1_pv_power_now
      device_class: "power"
      unit_of_measurement: "kW"
      state: >
            {{ (states('sensor.pv1_power') | float(default=0) + states('sensor.pv2_power') | float(default=0) ) * 1 }}
    - name: "PV Energy Daily"
      unique_id: foxess_inv1_pv_energy_daily
      device_class: "energy"
      unit_of_measurement: "kWh"
      state: >
            {{ ((states('sensor.pv1_daily') | float(default=0) + states('sensor.pv2_daily') | float(default=0) ) * 1 ) | round(2) }} 
    - name: "System Losses"
      unique_id: foxess_inv1_system_losses
      device_class: "power"
      unit_of_measurement: "kW"
      state: >
             {{ ((states('sensor.pv1_power') | float(default=0)
             + states('sensor.pv2_power') | float(default=0)
             + states('sensor.grid_consumption') | float(default=0)
             + states('sensor.battery_discharge') | float(default=0)
             - states('sensor.battery_charge') | float(default=0)
             - states('sensor.feed_in_power') | float(default=0)
             - states('sensor.load_power') | float(default=0) )) | round(2) }}
    - name: "Time Period 1 - Start Time"
      unique_id: foxess_inv1_time_period_1_start_time
      icon: "mdi:calendar-clock"
      state: >
        {% set raw_time = states('sensor.time_period_1_start') | int %}
        {% set hours = raw_time // 256 %}
        {% set minutes = raw_time - (hours * 256) %}
        {{ strptime(hours | string + ":" + minutes | string, '%H:%M').time() }}
    - name: "Time Period 1 - End Time"
      unique_id: foxess_inv1_time_period_1_end_time
      icon: "mdi:calendar-clock"
      state: >
        {% set raw_time = states('sensor.time_period_1_end') | int %}
        {% set hours = raw_time // 256 %}
        {% set minutes = raw_time - (hours * 256) %}
        {{ strptime(hours | string + ":" + minutes | string, '%H:%M').time() }}
    - name: "Time Period 2 - Start Time"
      unique_id: foxess_inv1_time_period_2_start_time
      icon: "mdi:calendar-clock"
      state: >
        {% set raw_time = states('sensor.time_period_2_start') | int %}
        {% set hours = raw_time // 256 %}
        {% set minutes = raw_time - (hours * 256) %}
        {{ strptime(hours | string + ":" + minutes | string, '%H:%M').time() }}
    - name: "Time Period 2 - End Time"
      unique_id: foxess_inv1_time_period_2_end_time
      icon: "mdi:calendar-clock"
      state: >
        {% set raw_time = states('sensor.time_period_2_end') | int %}
        {% set hours = raw_time // 256 %}
        {% set minutes = raw_time - (hours * 256) %}
        {{ strptime(hours | string + ":" + minutes | string, '%H:%M').time() }}
```

**Utility Meters (kept)**
```
utility_meter:
  load_daily:
    unique_id: foxess_inv1_load_daily
    source: sensor.load_sum
    cycle: daily
  pv1_daily:
    unique_id: foxess_inv1_pv1_daily
    source: sensor.pv1_sum
    cycle: daily
  pv2_daily:
    unique_id: foxess_inv1_pv2_daily
    source: sensor.pv2_sum
    cycle: daily
  bat_charge_daily:
    unique_id: foxess_inv1_bat_charge_daily
    source: sensor.bat_charge_sum
    cycle: daily
  bat_discharge_daily:
    unique_id: foxess_inv1_bat_discharge_daily
    source: sensor.bat_discharge_sum
    cycle: daily
  feedin_daily:
    unique_id: foxess_inv1_feedin_daily
    source: sensor.feedin_sum
    cycle: daily
  grid_daily:
    unique_id: foxess_inv1_grid_daily
    source: sensor.grid_consumption_sum
    cycle: daily
  losses_daily:
    unique_id: foxess_inv1_losses_daily
    source: sensor.losses_sum
    cycle: daily
```
**Integration sensors (kept)**
```
#Sensors turn power values into power/hour values for meters
sensor: 
  - method: left
    name: pv1_sum
    unique_id: foxess_inv1_pv1_sum
    platform: integration
    round: 2
    source: sensor.pv1_power
    unit_time: h
  - method: left
    name: pv2_sum
    unique_id: foxess_inv1_pv2_sum
    platform: integration
    round: 2
    source: sensor.pv2_power
    unit_time: h
  - method: left
    name: pv_total_sum
    unique_id: foxess_inv1_pv_total_sum
    platform: integration
    round: 2
    source: sensor.pv_power_now
    unit_time: h
  - method: left
    name: load_sum
    unique_id: foxess_inv1_load_sum
    platform: integration
    round: 2
    source: sensor.load_power
    unit_time: h
  - method: left
    name: bat_charge_sum
    unique_id: foxess_inv1_bat_charge_sum
    platform: integration
    round: 2
    source: sensor.battery_charge
    unit_time: h
  - method: left
    name: bat_discharge_sum
    unique_id: foxess_inv1_bat_discharge_sum
    platform: integration
    round: 2
    source: sensor.battery_discharge
    unit_time: h
  - method: left
    name: feedin_sum
    unique_id: foxess_inv1_feedin_sum
    platform: integration
    round: 2
    source: sensor.feed_in_power
    unit_time: h
  - method: left
    name: grid_consumption_sum
    unique_id: foxess_inv1_grid_consumption_sum
    platform: integration
    round: 2
    source: sensor.grid_consumption
    unit_time: h
  - platform: integration
    name: losses_sum
    unique_id: foxess_inv1_losses_sum
    source: sensor.system_losses
    unit_time: h
    method: left
    round: 2
```

**Comment by FozzieUK** [comment]
@calum-mcfarlane 
The _2 usually means that the sensor is still active when the new modbus sensors are added, but from what you have said they were showing as unavailable which is fine.

Were all the sensors appended with the _2 or just some - do you have any examples of them? 

Also when setting up did you set a friendly name or leave blank?

**Reply by calum-mcfarlane** [reply]
I left the friendly name field blank. I didn't check all the entities but the battery SoC, PV1 and PV2 Power were definitely all "_2".

The "PV Power Now" sensor (probably not its actual name) was unavailable, I presume because it was trying to sum two values that didn't exist anymore? 

I can try again and take better notes / pay attention to the right things this time around, today's data is already a mess :)

**Reply by FozzieUK** [reply]
Ok, yes best to leave the friendly name as blank.

You removed the pv_power_now which is why it is unavailable, you only needed to remove the first three sensors battery_discharge, battery_charge, grid_consumption - leave pv_power_now, pv_energy_daily and systems_losses all in place for now.

You can tidy up pv_power_now, pv_energy_daily later if you want (I recommended keeping them running for consistency of sensor names in your history) - they are provided internally by the new integration (pv_power_now is called pv_power), (pv_energy_daily is called solar_energy_today)

But you will need to keep the system losses sensor (note the change to feed_in_power sensor in my description is required).

Looks like you have the very latest StealthChesnut version with time periods, you will need to remove all the time period code, it is no longer needed (I think I may need to amend the upgrade notes to reflect this version)

Then if you can re-try what you did, making notes along the way.

I've always added in one extra step (I know others haven't and it works fine), but if you could try and do it like this please -

1) Remove the line modbus: !include custom_components/foxess/modbus485.yaml
2) Remove the 3 sensors battery_discharge, battery_charge, grid_consumption only
3) Remove the 4 time period sensors
4) change the feed_in_power template to use sensor.feed_in
5) restart HA (but give it 5 minutes afterwards, the latest version blocks HA shutdown which can take ages)
6) download Foxess modbus in HACS
7) restart HA (this is my extra step!)
8) Go to Settings, Integrations, search and add in the Foxess modbus integration - set it up with your config

Review your sensors

**Comment by calum-mcfarlane** [comment]
So - had another go. Followed all your steps, unfortunately seeing the same thing. Specifically: 

![image](https://github.com/nathanmarlor/foxess_modbus/assets/115465775/07ac353c-20a9-46e2-a663-caefafc22703)
![image](https://github.com/nathanmarlor/foxess_modbus/assets/115465775/8856d50d-7d50-40b2-ab74-03714804bb29)
It seems to collide with pretty much all the sensors in the old integration.

Do I need to go and delete all the "Modbus" sensors before I do the final reboot and install the new integration?

Edit: I'm also wondering if there is a way back from here without restoring my backup, ie can I delete the old Modbus sensors and rename the new FoxESS Modbus sensors, or will that ruin all the history....

**Reply by FozzieUK** [reply]
@calum-mcfarlane very weird.... 
ok lets try the simple thing first which is to click on one of those sensors (take battery_soc_2) , click on the cog in the corner and where it shows the entity_id underneath remove the _2 and click update. It will either allow it to be updated or it will say already exists - if it says already exists you will unfortunately have to sit with 2 screens open, the old and the new delete the old unavailable one and then quickly change the name of the new one (remove the _2).

I am reasonably sure your history will be preserved, but if you start with battery_soc and double check you'll know straight away.

**Reply by calum-mcfarlane** [reply]
Our replies crossed :O) But I think I just need to do the manual exercise, it seems to work fine. Worst case I start again from the backup!

**Reply by FozzieUK** [reply]
I've had to do this a few times on various systems, where you need to go through and remove the _2's... - and the history has always been fine, you shouldn't need the backup.

I never have been able to figure out what triggers it, a hidden internal HA sensor reference that has been corrupted which makes it happen?......  maybe one day we'll find it ;)

Good luck, let us know how it goes 👍

**Reply by nathanmarlor** [reply]
@FozzieUK this seems to be quite common and whilst we've done what we can to mitigate it seems to reoccur at random - has anyone reached out to the HA devs to ask for advice? I'd be happy to if not.

**Reply by calum-mcfarlane** [reply]
I wonder if it's a Unique ID thing. I've sorted all the sensors that had a "_2" on the end. My old PV Power Now sensor was defined as a template like this:

```
 - name: "PV Power Now"
      unique_id: foxess_inv1_pv_power_now
      device_class: "power"
      unit_of_measurement: "kW"
      state: >
            {{ (states('sensor.pv1_power') | float(default=0) + states('sensor.pv2_power') | float(default=0) ) * 1 }}
```
 Now I have two, one with my old and one with the new:
![image](https://github.com/nathanmarlor/foxess_modbus/assets/115465775/1a900af8-9077-4fc2-89e9-e38165415c42)

I can see PV Now from the new integration is working fine, but being a different sensor name it won't preserve the same history. Could I rename the **old sensor** to the **new name** in order to preserve the history, I wonder...

EDIT: No of course I can't, can't have two entities with the same name...

If I rename the **new sensor** to the **old name**, am I then effectively forking the integration, would that be something I'd have to update every time I upgraded it?

The issue is that this is one of the data points I **do** want to track over the longer term...

**Reply by FozzieUK** [reply, marked as answer]
@calum-mcfarlane - The old sensor was a template using the sum of pv1_power + pv2_power as it's source, both of those still exist in the new integration and that's why I said to leave the original PV Power Now template in place as it will continue to provide you with the sum of pv1 + 2 and all your history is intact - also if/when you upgrade the integration everything keeps working.

So just continue to use PV Power Now as you used to, and you've got a 'spare' sensor if in future you decide you want to move to the internally generated PV Power, but other than storage space there is no reason too.

You could remove the integration one from your logger (or disable it) if you want to keep your database controlled, you'll have so many new sensors with this integration you'll need to think about what you want to record / monitor anyway.

**Reply by calum-mcfarlane** [reply]
You are of course correct - thanks for the clarification. 

What was confusing the heck out of me was that I'd somehow messed up the YAML for the template sensors. However, because the "will HA still boot?" checker was giving me a green light it took me a little while to spot it (you can of course have incorrectly defined sensors that won't stop HA starting, but they won't actually work, either!)

I've got all those templates fixed now so I'm back to logging the right stuff in Maria/Influx. You're right, I will need to look again at my recorder settings and make sure I'm not inadvertently logging stuff I don't need.

**Reply by FozzieUK** [reply]
Great stuff, hours of fun :wink:

**Reply by canton7** [reply]
Just disable sensors that you don't want (rather than going to the bother of excluding then from the recorder). That means we won't even bother fetching or reporting then to ha, and they won't appear run your sensor list.

**Reply by FozzieUK** [reply]
@canton7 actually whilst you mention it, can I double check if you disable the sensors you don’t want do the number of register reads re-calculate.

On the W610 with 8 registers read at a time, the latest version is reporting 83 entities which is getting too close to the 10s poll.. a friends system is reporting lots of ‘previous refresh in process’, i’m just trying to fix it without jumping in my car and swapping him over to UDP 👍

**Reply by canton7** [reply]
Ah interesting. I do test the W610 with tcp to make sure we're not exceeding its limits, but maybe mine was behaving better than average. I might have to slow the poll rate for W610+tcp.

Yes, the specific reads to do are calculated on each poll (which is overkill, as the integration actually gets restarted when entities are disabled/enabled), so it will respond as you disable sensors.

**Reply by canton7** [reply]
@FozzieUK Is this system running both foxess_modbus and foxess_em by any chance?

**Reply by FozzieUK** [reply]
@canton7 - no that system is a simple foxess modbus only, very low load. I disabled a lot of the extra sensors and it calmed down nicely - i've just got back from there and have switched it to UDP, it was taking nearly 8 seconds to poll before - now around 1s with everything enabled.. just amazing 😄 

I have noticed that I occasionally get the previous refresh in progress message, when I investigated the timings around the time of the warning I could see there were over 15 seconds between reads.. (normally in the milliseconds) - I was just starting to investigate all my integrations to see which might be blocking, it doesn't happen very often  - but yes I do have Nathan's EM running (using modbus)

**Reply by dreampi** [reply]
Can I ask, Is there any benefit when using UDP protocol over TCP?

**Reply by canton7** [reply]
For the W610 it is significantly quicker - we can poll everything in less than 1s over UDP, compared to 10s with TCP. For other adapters, not so much.

**Reply by dreampi** [reply]
Thanks for the response. I’m using an EW11 on TCP, and it allows me to poll at 1s without any issues. Do you think I might be able to get away with switching it to UDP and see if I can poll in less than a second?

**Reply by calum-mcfarlane** [reply]
Make sure you have plenty of room for your database if you do that!

**Reply by canton7** [reply]
UDP won't magically make polling faster. This only affects the W610 which has problems with its TCP stack that slow TCP down significantly.

I don't think we even let you configure a poll speed faster than 1s.

**Reply by dreampi** [reply]
If you set the poll rate to 0, your sensors will change on every update they receive from your inverter. It has worked very well on a LAN connection (for obvious reasons); however, it hasn’t worked as well with Modbus TCP.

**Reply by canton7** [reply]
Hmm? We don't receive updates from the inverter - we have to go and poll for them. I'm not sure what will happen if you set a poll rate of 0, I'll check tomorrow - I suspect HA will be telling us to poll as quickly as it can, and we'll throw a ton of warnings because we'll stoll be in the middle of the previous poll most of the time. Have you checked the log to see what's going on, as the settings dialog tells you to?

Quite frankly it's a bug that we allow that. I'll fix it.

**Reply by canton7** [reply]
Also, lan and RS485 (we use ModbusTCP with both) work the same here. What's the "for obvious reasons" you refer to?

**Reply by dreampi** [reply]
You certainly get a tremendous number of warnings in the log when you try this. I didn’t receive any warnings when I was doing it through LAN though

**Comment by calum-mcfarlane** [comment]
Seem to have answered my own second question, it does look like if I just delete the old entity and rename the new one the history sorts itself out...

**Comment by FozzieUK** [comment]
> @FozzieUK this seems to be quite common and whilst we've done what we can to mitigate it seems to reoccur at random - has anyone reached out to the HA devs to ask for advice? I'd be happy to if not.

@nathanmarlor No I don't believe so  - whenever i've seen it happen (on other peoples systems), it's because of either not removing the old modbus include, or HA being blocked from restarting because of modbus timeouts before the new integration is added - and I suspect part of the problem is that once it goes wrong, you have to delete the integration and all of the _2 sensors or the integration will continue to use them next time it's added.

It happened to me right at the beginning, but that was a definite case of my HA blocking shutdown, i've built maybe 6 systems since and every one has been fine... confusing.. :zany_face:

It would certainly be helpful to me to understand the mechanism of registering sensors, and whether using different databases (sqlite, mariadb etc..) might be part of it.

**Reply by FozzieUK** [reply]
@nathanmarlor 
Update: just reading through the entity registration process, if i’m reading it correctly unique_id plays a major part in stopping entities being duplicated, so if an entity had a unique_id set, it would prevent other entities taking over that entity_id. 
I’m now wondering whether that is what’s caused this to happen as Calum upgraded from the very latest StealthChesnut modbus include file which was fairly recently updated to include unique_id’s to the sensor description - whereas every previous version had no unique_id’s. ??

**Reply by canton7** [reply]
Hah that'll be a bummer - I was the one who contributed those unique_ids!

Although, the H3 yaml has had unique ids for ages, and I'm reasonably sure we've had people with H3s migrate without issue

**Reply by FozzieUK** [reply]
:rofl: if that’s it i’m not sure there’s much we can do for those using the latest modbus include, other than talk them through the delete and update method that Calum’s just done.

Hopefully there won’t be many of them as new users will likely have gone straight to this integration and won’t have the legacy to worry about.

**Reply by calum-mcfarlane** [reply]
Heh, I did update the YAML defining the sensors so they all had unique IDs, could have saved myself the trouble it would seem. This is my **/config/custom_components/foxess/modbus485.yaml** (no longer in active use but this is what was on the system before I changed things up.

(Yes I was scanning some of the sensors every two seconds, don't judge 😅 )

```
# v0.9
# Created by https://github.com/StealthChesnut/HA-FoxESS-Modbus
# Modbus Config for Fox ESS Hybrid H1 Inverter
  
# ---------------------------Direct LAN Connection----------------------------------------
#  For use when connecting direct to LAN port of inverter
#
#- name: HA-FoxESS-Modbus-LAN
  type: tcp
  host: !secret ModBusAdapterIP # Set to IP address of the ModBus to TCP adapter
  port: 502
#
# ---------------------------------------------------------------------------
# Uncomment the sensors you wish to use

  sensors:
    - name: "PV1-Voltage"
      unique_id: foxess_inv1_pv1_voltage
      scan_interval: 30
      slave: 247
      address: 11000
      state_class: measurement
      unit_of_measurement: "V"
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: input
      device_class: voltage
    - name: "PV1-Current"
      unique_id: foxess_inv1_pv1_current
      scan_interval: 30
      slave: 247
      address: 11001
      state_class: measurement
      unit_of_measurement: "A"
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: input
      device_class: current
    - name: "PV1-Power"
      unique_id: foxess_inv1_pv1_power
      scan_interval: 2
      slave: 247
      address: 11002
      state_class: measurement
      unit_of_measurement: "kW"
      data_type: int16
      scale: 0.001
      precision: 3
      input_type: input
      device_class: power
    - name: "PV2-Voltage"
      unique_id: foxess_inv1_pv2_voltage
      scan_interval: 30
      slave: 247
      address: 11003
      state_class: measurement
      unit_of_measurement: "V"
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: input
      device_class: voltage
    - name: "PV2-Current"
      unique_id: foxess_inv1_pv2_current
      scan_interval: 30
      slave: 247
      address: 11004
      state_class: measurement
      unit_of_measurement: "A"
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: input
      device_class: current
    - name: "PV2-Power"
      unique_id: foxess_inv1_pv2_power
      scan_interval: 2
      slave: 247
      address: 11005
      state_class: measurement
      unit_of_measurement: "kW"
      data_type: int16
      scale: 0.001
      precision: 3
      input_type: input
      device_class: power
    - name: "Battery-SoC"
      unique_id: foxess_inv1_battery_soc
      scan_interval: 30
      slave: 247
      address: 11036
      state_class: measurement
      unit_of_measurement: "%"
      data_type: int16
      input_type: input
      device_class: battery
    - name: "Battery-Temp"
      unique_id: foxess_inv1_battery_temperature
      scan_interval: 60
      slave: 247
      address: 11038
      state_class: measurement
      unit_of_measurement: "°C"
      scale: 0.1
      precision: 1
      data_type: int16
      input_type: input
      device_class: temperature
    - name: "Battery-Discharge-Power"
      unique_id: foxess_inv1_battery_power
      scan_interval: 2
      slave: 247
      address: 11008
      state_class: measurement
      unit_of_measurement: "kW"
      data_type: int16
      scale: 0.001
      precision: 3
      input_type: input
      device_class: power
    - name: "Load Power"
      unique_id: foxess_inv1_load_power
      scan_interval: 2
      slave: 247
      address: 11023
      state_class: measurement
      unit_of_measurement: "kW"
      data_type: int16
      scale: 0.001
      precision: 3
      input_type: input
      device_class: power
    - name: "InvBatVolt"
      unique_id: foxess_inv1_inverter_battery_voltage
      scan_interval: 30
      slave: 247
      address: 11006
      state_class: measurement
      unit_of_measurement: "V"
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: input
    - name: "InvBatPower"
      unique_id: foxess_inv1_inverter_battery_power
      scan_interval: 2
      slave: 247
      address: 11007
      state_class: measurement
      unit_of_measurement: "kW"
      data_type: int16
      scale: 0.01
      precision: 2
      input_type: input
    - name: "RVolt"
      unique_id: foxess_inv1_grid_voltage_R
      scan_interval: 30
      slave: 247
      address: 11009
      state_class: measurement
      unit_of_measurement: "V"
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: input
      device_class: voltage
    - name: "RCurrent"
      unique_id: foxess_inv1_inv_current_R
      scan_interval: 30
      slave: 247
      address: 11010
      state_class: measurement
      unit_of_measurement: "A"
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: input
      device_class: current
    - name: "RFreq"
      unique_id: foxess_inv1_grid_frequency
      scan_interval: 30
      slave: 247
      address: 11014
      state_class: measurement
      unit_of_measurement: "Hz"
      data_type: int16
      scale: 0.01
      precision: 3
      input_type: input
      device_class: frequency
    - name: "EPS RVolt"
      unique_id: foxess_inv1_eps_rvolt
      scan_interval: 30
      slave: 247
      address: 11015
      state_class: measurement
      unit_of_measurement: "V"
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: input
    - name: "Grid CT"
      unique_id: foxess_inv1_grid_ct
      scan_interval: 2
      slave: 247
      address: 11021
      state_class: measurement
      unit_of_measurement: "kW"
      data_type: int16
      scale: 0.001
      precision: 3
      input_type: input
    - name: "CT2 Meter"
      unique_id: foxess_inv1_ct2
      scan_interval: 1
      slave: 247
      address: 11022
      state_class: measurement
      unit_of_measurement: "kW"
      data_type: int16
      scale: 0.001
      precision: 3
      input_type: input
    - name: "InvTemp"
      unique_id: foxess_inv1_inverter_temperature
      scan_interval: 30
      slave: 247
      address: 11024
      state_class: measurement
      unit_of_measurement: "°C"
      data_type: int16
      scale: 0.1
      precision: 1
      device_class: temperature
      input_type: input
    - name: "AmbTemp"
      unique_id: foxess_inv1_ambient_temperature
      scan_interval: 30
      slave: 247
      address: 11025
      state_class: measurement
      unit_of_measurement: "°C"
      data_type: int16
      scale: 0.1
      precision: 1
      device_class: temperature
      input_type: input
    - name: "BatVolt"
      unique_id: foxess_inv1_battery_voltage
      scan_interval: 30
      slave: 247
      address: 11034
      state_class: measurement
      unit_of_measurement: "V"
      data_type: int16
      scale: 0.1
      precision: 1
      device_class: voltage
      input_type: input
    - name: "Temp"
      unique_id: foxess_inv1_temperature
      scan_interval: 30
      slave: 247
      address: 11035
      state_class: measurement
      unit_of_measurement: "°C"
      data_type: int16
      scale: 0.1
      precision: 1
      device_class: temperature
      input_type: input
    - name: "Min SoC"
      unique_id: foxess_inv1_min_soc
      scan_interval: 60
      slave: 247
      address: 41009
      state_class: measurement
      unit_of_measurement: "%"
      data_type: int16
      input_type: input
      device_class: battery
    - name: "Min SoC (On Grid)"
      unique_id: foxess_inv1_min_soc_on_grid
      scan_interval: 60
      slave: 247
      address: 41011
      state_class: measurement
      unit_of_measurement: "%"
      data_type: int16
      input_type: input
      device_class: battery
    - name: "Time Period 1 - Start"
      unique_id: foxess_inv1_time_period_1_start
      address: 41002
      scan_interval: 60
      slave: 247
      input_type: input
    - name: "Time Period 1 - End"
      unique_id: foxess_inv1_time_period_1_end
      address: 41003
      scan_interval: 60
      slave: 247
      input_type: input
    - name: "Time Period 2 - Start"
      unique_id: foxess_inv1_time_period_2_start
      address: 41005
      scan_interval: 60
      slave: 247
      input_type: input
    - name: "Time Period 2 - End"
      unique_id: foxess_inv1_time_period_2_end
      address: 41006
      scan_interval: 60
      slave: 247
      input_type: input

    - name: "BMS Cell mV High"
      unique_id: foxess_inv1_bms_cell_mv_high
      address: 11045
      scan_interval: 5
      slave: 247
      input_type: input
      device_class: voltage
      unit_of_measurement: "mV"
    - name: "BMS Cell mV Low"
      unique_id: foxess_inv1_bms_cell_low
      address: 11046
      scan_interval: 5
      slave: 247
      input_type: input
      device_class: voltage
      unit_of_measurement: "mV"
    - name: "BMS Charge Rate"
      unique_id: foxess_inv1_bms_charge_rate
      address: 11041
      scan_interval: 30
      slave: 247
      input_type: input
      device_class: current
      unit_of_measurement: "A"
      scale: 0.1
    - name: "BMS Discharge Rate"
      unique_id: foxess_inv1_bms_discharge_rate
      address: 11042
      scan_interval: 30
      slave: 247
      input_type: input
      device_class: current
      unit_of_measurement: "A"
      scale: 0.1
    - name: "BMS Cell Temp Low"
      unique_id: foxess_inv1_bms_cell_temperature_low
      scan_interval: 30
      slave: 247
      address: 11044
      state_class: measurement
      unit_of_measurement: "°C"
      data_type: int16
      scale: 0.1
      precision: 1
      device_class: temperature
      input_type: input
    - name: "BMS Cell Temp High"
      unique_id: foxess_inv1_bms_cell_temperature_high
      scan_interval: 30
      slave: 247
      address: 11043
      state_class: measurement
      unit_of_measurement: "°C"
      data_type: int16
      scale: 0.1
      precision: 1
      device_class: temperature
      input_type: input
    - name: "BMS Watthours Total"
      unique_id: foxess_inv1_bms_watthours_total
      address: 11049
      scan_interval: 60
      slave: 247
      input_type: input
      unit_of_measurement: "Ah"
      device_class: energy
    - name: "BMS kWh Remaining"
      unique_id: foxess_inv1_bms_kwh_remaining
      address: 11037
      scan_interval: 60
      slave: 247
      input_type: input
      scale: 0.01
      precision: 2
      device_class: energy
      unit_of_measurement: "kWh"

  binary_sensors:
    - name: "Time Period 1 - Enabled"
      unique_id: foxess_inv1_time_period_1_enabled
      address: 41001
      scan_interval: 60
      slave: 247
      input_type: input
    - name: "Time Period 2 - Enabled"
      unique_id: foxess_inv1_time_period_2_enabled
      address: 41004
      scan_interval: 60
      slave: 247
      input_type: input

  # !include sensors.yaml
```
