### DISCUSSION TITLE
Migration from StealthChestnut: Invalid config for [sensor.template]: [state] is an invalid option

### DISCUSSION THREAD

**Discussion by phips** [nathanmarlor/foxess_modbus#471] [Support] [answered]
Hello,

In the excellent migrating from HA FoxESS Modbus docs there's a bit about reconfiguring "FeedIn Power". However, when I use the config there I get this error:

<img width="1027" alt="Screenshot 2023-12-12 at 17 37 23" src="https://github.com/nathanmarlor/foxess_modbus/assets/329022/ff9f803e-555c-4dd7-bc02-aaeb50d2e3d6">

It used to be a 'value_template', is that what I should be using versus 'state'?

I'm on HA version 2023.7.2

Many thanks!

**Comment by FozzieUK** [comment, marked as answer]
If your old sensor was a value_template it was in the 'old' format and in a different section of the configuration.yaml (usually near the start)

You have a couple of options, if further down in your configuration.yaml you have a section that looks like this -
```
template:
  - sensor:
```

Then you can remove the old template sensor and add this new sensor under the template section so that it looks like this

```
template:
  - sensor:
    - name: "Feed In Power"
      unique_id: foxess_inv1_feed_in_power
      device_class: "power"
      unit_of_measurement: "kW"
      state: >
          {{ states('sensor.feed_in') | float(default=0) }}
```

**OR** if you prefer you can modify the sensor in the old 'platform tenplate' section

in which case you would simply replace the old sensor with this

```
  - platform: template
    sensors:
      feed_in_power:
        device_class: "power"
        friendly_name: "Feed in Power"
        unit_of_measurement: "KW"
        value_template: "{{ states('sensor.feed_in') | float(default=0) }}"
```
