### DISCUSSION TITLE
Maximum force charge kw amount limited to 6kw

### DISCUSSION THREAD

**Discussion by sabbie-github** [nathanmarlor/foxess_modbus#537] [Q&A] [answered]
Not sure if I am doing something wrong, but the max force charge amount seems to be limited to 6kw. Is there a reason for this? Can it be set to more? With a 20.8kw battery system being depleted to 20%, the 6kw of force charge amount is too low. Thank you!

system
H1-5.0-E inverter
lan connection
foxess modbus v 1.10.0b6

![image](https://github.com/nathanmarlor/foxess_modbus/assets/108624802/b2d6ceaa-6df7-45bd-a71b-839b1640a0eb)
![image](https://github.com/nathanmarlor/foxess_modbus/assets/108624802/c3b837dc-9bb3-46db-b3a1-17c342df2d93)

**Comment by canton7** [comment]
Unless I'm vastly misunderstanding something, you've got a H1-5.0, which can output 5kW?

![image](https://github.com/nathanmarlor/foxess_modbus/assets/568104/91ad68ac-e493-4ed5-b558-09ea3c14ebe6)

**Reply by sabbie-github** [reply]
Must be my mistake. I understood it to be the amount of KW that will be force charged "into" the battery and not the output "speed" (for lack of better wording).
It is all clear now - the force charge/discharge input here regulates the output and not the amount charged. Correct?
If so, we can close this qna and thank you for clarifying.

**Reply by canton7** [reply, marked as answer]
The power of your inverter is how quickly it can turn AC current into DC current, and vice versa (simply put).

The battery is DC. Mains, and the grid, is AC. Therefore to charge the battery from the grid you need to turn AC into DC, and to discharge the battery to the grid you need to turn DC to AC. Both of these operations are therefore limited by the power of your inverter.

Force discharge discharges the battery to the grid. The speed at which you can do this is limited by your inverter size.

**Reply by canton7** [reply]
> With a 20.8kw battery system

You have a 20kWh battery, not a 20kW battery.

Watts is a measure of power. Think of it as how fast a river is flowing. Watt-hours is a measure of energy -- if your river is "flowing" at 1kW (1000 Watts), then a Kilowatt-hour is the amount of water which passes under a bridge on that river in the space of an hour. 

So if you have a lake which has a capacity of 2kWh, and a river which is draining it at 1kW, it will take the river 2 hours to empty the lake.

The force discharge power is the speed of the river. Your battery is a lake which is being drained by the river.

**Reply by sabbie-github** [reply]
thank you for clarifying, I assumed incorrectly that this was a setting for x kWh being put into the battery.

**Reply by sabbie-github** [reply]
If I only have a LAN connection to the inverter and using the modbus integration, is it correct to say that I wont be able to use the "modbus charge period card" as the inverter is not available to select when setting up that card, but I can still write my own automation that sets the force charge to "Enabled" for a period of time?

**Reply by FozzieUK** [reply]
Yes that's correct, the original charge periods cannot be set over the LAN connection.

It also worth mentioning that the LAN interface has been discontinued on the latest firmware versions (in fact on latest inverters the LAN port has been removed) and FoxESS have confirmed that this interface will no longer be supported in favour of RS485 connections.

On the force charge automation, I think this post hopefully answers how it can be done - https://github.com/nathanmarlor/foxess_modbus/discussions/513#discussioncomment-8143425

**Reply by sabbie-github** [reply]
Thank you! Does that mean that if I want to carry on using LAN connection for modbus, I should not update the inverter to future firmware?

As for the automation - I only wanted to do something very simple, that is to use night electricity to force charge the batteries and keep force charge on until 4.30am even when the batteries are full, so that the car charger can pull from the grid during this time and not from the battery. For me this simple automation would do the trick I think:

```
alias: FoxESS Force Charge Timer
description: Force Charge from 0:10am to 4:30am
trigger:
  - platform: time
    at: "00:10:00"
    id: ID_ON
  - platform: time
    at: "04:30:00"
    id: ID_OFF
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - ID_ON
        sequence:
          - service: select.select_option
            metadata: {}
            data:
              option: Force Charge
            target:
              entity_id: select.foxess_lan_force_charge_mode
      - conditions:
          - condition: trigger
            id:
              - ID_OFF
        sequence:
          - service: select.select_option
            metadata: {}
            data:
              option: Disable
            target:
              entity_id: select.foxess_lan_force_charge_mode
mode: single
```

**Reply by FozzieUK** [reply]
Yes unfortunately that is the case with new firmware for the inverter, so perhaps longer term have a think about switching to RS485 for control.

I thought the latest beta allowed force charge work mode selection over LAN on the H1 in which case you would simply change the work mode to force charge to start

```
          - service: select.select_option
            metadata: {}
            data:
              option: Force Charge
            target:
              entity_id: select.work_mode
 ```
And back to self-use when finished

 ```
          - service: select.select_option
            metadata: {}
            data:
              option: Self Use
            target:
              entity_id: select.work_mode
 ```
 (Replace select.work_mode with the name of your entity select.foxess_lan_work_mode ?)
 
 but I’ll let @canton7 confirm FC work mode is available on H1 over LAN
