### DISCUSSION TITLE
Battery SoC to multiple decimal places

### DISCUSSION THREAD

**Discussion by WyndStryke** [nathanmarlor/foxess_modbus#801] [General]
I needed a more accurate figure for sensor.battery_soc for an automation, is there any way to get this direct from the inverter?  (KH7, EC4300-H4, manager 1.37).

I do have a workaround which is to use an integral sensor on sensor.batinvpower, take a snapshot of it whenever SoC changes, and then track the difference & add it to the battery SoC.  

Seems to work OK when steadily force charging or discharging, but seems off if more complex stuff is happening.  For example, if the workmode transitions into Force Discharge, the inverter's SoC often seems to jump up to the next percentage as the mode changes, and then takes a while to drop back down, as if the SoC was calculated differently, or was stale, and updated by the mode change (illustrated by the jump from 71 to 72 in the example).

So my question is really ... is there a better/simpler way to do it?

`input_number.foxess_battery_charge_at_soc (kWh)`

```
sensor.foxess_invbatpower_adjusted  kW

{% set invbatpower_original = states('sensor.invbatpower') | float %}
{% set pvpower = (states('sensor.pv_power') | float) - (states('sensor.rpower') | float) %}
{% if pvpower  < 0 %}
  {% set pvpower = 0 %}
{% endif %}
{% set feedin_first_silent_charge = -0.060 %}
{% if pvpower + feedin_first_silent_charge < 0 %}
  {% set feedin_first_silent_charge = -pvpower %}
{% endif %}
{% if (invbatpower_original == 0)  and states('select.work_mode') == 'Feed-in First' %}
  {# Battery seems to be trickle charged at 60W during feed-in First when there is PV and no draw, despite invbatpower being zero #}
  {% set invbatpower_actual = invbatpower_original + feedin_first_silent_charge %}
{% else %}  
  {% set invbatpower_actual = invbatpower_original %}
{% endif %}
{{ invbatpower_actual }}
```

```
alias: FoxESS_battery_charge_snapshot
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.battery_soc
    id: SoC_trigger
conditions: []
actions:
  - if:
      - condition: trigger
        id:
          - SoC_trigger
    then:
      - action: input_number.set_value
        metadata: {}
        data:
          value: >-
            {% set reiman_integral_SoC =
            states('sensor.foxess_battery_soc_from_invbatpower') | float %} {%
            set SoC_perc_starting_charge = 0 %} {% if
            ((trigger.from_state.state|int) > (trigger.to_state.state|int)) %}
            {% set SoC_perc_starting_charge =
            (states('sensor.bms_kwh_remaining')| float / 100) %} {% endif %} {{
            reiman_integral_SoC + SoC_perc_starting_charge }}
        target:
          entity_id: input_number.foxess_battery_charge_at_soc
mode: single
```

`sensor.foxess_battery_soc_from_invbatpower  integral, input sensor FoxESS_invbatpower_adjusted, left Riemann sum, 10s interval`

```
sensor.foxess_battery_soc_exact    %

{% set delta_percentage = 0 %}
{% set kWh_capacity = (states('sensor.bms_kwh_remaining') | float) %}
{% set current_bat_charge =(states('input_number.foxess_battery_charge_at_soc') | float) - (states('sensor.foxess_battery_soc_from_invbatpower') | float) %}
{% set current_bat_charge_perc = (current_bat_charge / kWh_capacity) * 100 %} 
{% if current_bat_charge_perc < 0 %}
  {% set current_bat_charge_perc = 0 %}
{% endif %}
{% if current_bat_charge_perc > 0.99 %}
  {% set current_bat_charge_perc = 0.99 %}
{% endif %}
{{ (states('sensor.battery_soc') | float) + current_bat_charge_perc }}
```

And then using all that, I can calculate a target charge or discharge speed for a given SoC and time.  I found that just using the standard sensor.battery_soc caused too many artifacts close to the target time.  It'd be nice if there were a better way to do it though.

This is what it looks like in use:

![SoC_calculation](https://github.com/user-attachments/assets/0358a40f-e546-4d36-9293-22bb96569d70)

```
input_number.foxess_daytime_discharge_bottom_soc


sensor.foxess_discharge_speed_for_midnight    kW

{% set target_time = '23:55:00' %}
{% set discharge_period_hours = 8 %}
{% set inverter_rating_kW = 7.0 %}
{# Account for battery efficiency losses during discharge #}
{% set battery_selfuse = 0.085 %}
{% set soc_target = states('input_number.foxess_daytime_discharge_bottom_soc') | float + 0.95 %}
{% set hours_until_target_time = ((today_at(target_time) - now()).total_seconds()/ 3600) %}
{% if hours_until_target_time < 0.0 %}
   {% set hours_until_target_time = 0.0 %}
{% endif %}
{% if hours_until_target_time > discharge_period_hours %}
   {# Don't calculate discharge speed if not in discharge period #}
   {% set hours_until_target_time = 0.0 %}
{% endif %}
{% set soc_delta = (states('sensor.foxess_battery_soc_exact') | float) - soc_target %}
{% if soc_delta < 0.0 %}
   {% set soc_delta = 0.0 %}
{% endif %}
{% set kwh_delta = (states('sensor.bms_kwh_remaining') | float) * soc_delta / 100.0 %}
{% if kwh_delta < 0.0 %}
   {% set kwh_delta = 0.0 %}
{% endif %}
{% if hours_until_target_time > 0.0 and kwh_delta > 0 %}
  {% set kw_for_target = ((kwh_delta / hours_until_target_time) - battery_selfuse) | round(3)  %}
{% else %}  
  {% set kw_for_target = 0.0 %}
{% endif %}
{% if kw_for_target < 0 %}
   {% set kw_for_target = 0.0 %}
{% endif %}
{% if kw_for_target > inverter_rating_kW %}
   {% set kw_for_target = inverter_rating_kW %}
{% endif %}
{{ kw_for_target }}
```
