### ISSUE TITLE
Discrepancy in acceptable Charge Period time ranges in integration vs those in the FoxCloud App

### ISSUE THREAD

**Issue by Grimroper** [nathanmarlor/foxess_modbus#367]
Hello

In the FoxCloud app when setting the time range to start and end your charging you can enter a matching time.  For example you can enter a time of 00:00 to start and a time of 00:00 to end if you wanted to.

Previously the app wouldnt let you do that, it gave an error that said something like you cant have times overlapping.  But now, probably when the app was updated to remove the "Enable force charge" option, you can now enter a matching start and end time.

The reason I want to set the matching times is because if you have "Enable Charge From Grid" on and also have a time range of say 00:30 to 01:30 the battery wont charge during that period but it also wont discharge for that hour either.  Power will come from the grid or at least thats my experience of what happens.

However the integration still forces to you not overlap the times.  If you try to enter the same time in each field it says 

"Failed to call service foxess_modbus.update_charge_period. value must be at least 00:01:00 for dictionary value @ data['end']. Got None"

For the message above I entered a start and end time of 00:00.  See the example Yaml below

I admit that being forced to set this by 1 minute is not a big deal but its probably a good idea to bring the integration inline with how the App behaves.  Potentionally removing the "Enable force charge" option as well?

I have v1.6.2 of the Foxess_modbus integration installed

## Configuration

```yaml
service: foxess_modbus.update_charge_period
data:
  inverter: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  enable_force_charge: false
  enable_charge_from_grid: false
  start: "00:00:00"
  end: "00:00:00"
  charge_period: "1"
```
