### ISSUE TITLE
"Unable to prepare setup for platform foxess_modbus.binary_sensor: Platform not found (No module named 'custom_components.foxess_modbus.binary_sensor')."

### ISSUE THREAD

**Issue by calum-mcfarlane** [nathanmarlor/foxess_modbus#430]
## Configuration

```yaml
Logger: homeassistant.setup
Source: setup.py:359
First occurred: 09:07:14 (1 occurrences)
Last logged: 09:07:14

Unable to prepare setup for platform foxess_modbus.binary_sensor: Platform not found (No module named 'custom_components.foxess_modbus.binary_sensor').
```

## Describe the bug

Yesterday I tried to upgrade to the latest version of the integration and custom card via HACS. The card upgrade went fine, but the integration upgrade got 'stuck' (progress wheel kept on going and going) - all sensors for the inverter became "unavailable". I tried to re-download the previous version, which got most of the sensors working, but the status flags for both charge periods remain unavailable. In addition, I see the error message posted above in the logs.

I also see that the charge period update service is no longer working:

![image](https://github.com/nathanmarlor/foxess_modbus/assets/115465775/b3dc21eb-8fbf-4983-a4ee-14800b97af41)
I only have one inverter so I haven't ever given mine a "friendly name" when setting up the integration

## Debug log

```text

If I enable debug logging for the integration I just see lots of sensors being read but no further errors - it only seems to throw that error when trying to set up, but after that's gone wrong, other things seem to fail silently

```
